repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch
    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-yaml
    - id: check-executables-have-shebangs
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
    # Cross platform
    - id: detect-private-key
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    # Terraform
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    # - id: terraform_checkov
    # - id: terraform_providers_lock
    # - id: terraform_tfsec
    # - id: terrascan
    - id: tfupdate
      args:
      - --args=terraform --version '>= 1.5.6'
    - id: tfupdate
      args:
      - --args=provider --version '>= 3.71.0' azurerm
    # - id: infracost_breakdown
    #   args:
    #     - --args=--path=.
    #   verbose: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key
